### ISSUE TITLE
New update is not backwards-compatible

### ISSUE THREAD

**Issue by alecrivers** [petrikosk/rsruckig#2]
Great package, thanks for it!

Small note: it seems version 1.1.1 is not backwards-compatible with 1.0.2, which causes issues because Cargo assumes that it can install the latest semver-compatible build. Easy enough to fix by setting

`rsruckig = "=1.0.2"`

but I didn't even know Cargo did that, so it took me a while to figure it out :P Specifically I was hitting issues with the fact that the Ruckig struct now has two generics instead of one.

**Comment by petrikosk** [comment]
I am happy to hear that you have found the package useful!

It seems there was a mistake in versioning. I should have bumped the major version, not minor because of the breaking changes. As there is no way to delete a version from crates.io, I think we just need to accept this as is for now, and and I am glad to hear you have found a workaround. However, these changes are here to stay as they originate from the original Ruckig C++ version, which allows to declare number of DOF as a template parameter or dynamically. In general, the change is minor, so it depends on the size of your application, but it may make sense to refactor it to reflect the changes in the library.
